#!/usr/bin/env perl

# Copyright (C) 2017 Nickolas Burr <nickolasburr@gmail.com>
# License under WTFPL (http://www.wtfpl.net/txt/copying/)

# git-track: Track lifetime changes (including renames) of a file
# throughout the complete history of a Git repository
use 5.008;
use Getopt::Long;
use Data::Dumper;
use strict;
use warnings;

# specific user error type messages
my $repo_not_found_error   = "Not a Git repository, exiting the script";
my $invalid_pathspec_error = "Not a valid pathspec, exiting the script";
my $invalid_usage_error    = "Usage: git track [[--first|-f] | [--func|-F] | [--last|-l] | [--lines|-L] | [--reverse|-r]] filename";

# store length of `@ARGV`
my $argc = @ARGV;

# if `system` returns a non-zero exit status, meaning the
# current directory is not a Git repository, kill the script
!system("git rev-parse --is-inside-work-tree >/dev/null 2>&1") or die "$repo_not_found_error";

# if no arguments were given, emit an error and kill the script
$argc or die "$invalid_usage_error";

# store the last argument (which should be
# the filename the user is trying to track)
# and remove it from `@ARGV` array
my $filename = pop @ARGV;

# verify `$filename` is a valid pathspec
if (! -e $filename) {
	die "$invalid_pathspec_error";
}

# flag options passed to the script
my %flags;

# optionally set default view for diffs
# shown in `git log` (defaults to inline)
my $git_log_default_diff = "side-by-side";

# default format to use for `git log --format` flag option
my $git_log_default_format = "%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset%n";

# default `git log` flag options
my @git_log_flags = (
	"--follow",
	"--format='$git_log_default_format'",
	"--graph",
	"--no-merges",
	"--patch-with-stat"
);

# default argument values for flag options
my %dargs = (
	"first" => "A",
	"last"  => 1,
	"lines" => 1
);

# set argument value(s) for `$flag`,
# whether given to the flag or default
sub set_args {
	my $flag = shift;
	my $arg  = shift;
	if (!$arg) {
		$flags{$flag} = $dargs{$flag};
	} else {
		$flags{$flag} = $arg;
	}
}

# require flag options to be case-sensitive, positionally interchangeable,
# and able to accept a range of arguments, based on the flag
Getopt::Long::Configure(
	'no_ignore_case',
	'no_auto_abbrev',
	'no_getopt_compat'
);

# get flag options and arguments passed to the script
GetOptions(
	\%flags,
	'first|f=i{0,1}',
	'func|F=s{1,1}',
	'last|l=i{0,1}' => \&set_args,
	'lines|L=i@{1,2}',
	'reverse|r'
) or die "$invalid_usage_error";

# base components of `git log` shell command, represented
# as an array to make it easier to pass to `system` builtin
my @git_log = (
	"git",
	"log"
);

sub get_first_n_commits {
	# @todo: Get first n commits for a file
}

sub get_format_rflag {
	my $flag = shift;
	my @args = shift;
	if ($flag eq "first") {
		my $num = shift @args;
		if (!$num) {
			return "--diff-filter=A";
		} else {
			# this is a placeholder until I finalize
			# building `&get_first_n_commits` subroutine
			return "--diff-filter=C";
		}
	# @fix: There seems to be some type of issue
	# that's causing Git to reject the string of
	# the function name we're passing to `git log`
	} elsif ($flag eq "func") {
		my $funcname = shift @args;
		return "-L ^:$funcname:$filename";
	} elsif ($flag eq "last") {
		my $num = shift @args;
		if (!$num) {
			return "--max-count=1";
		} else {
			return "--max-count=$num";
		}
	} elsif ($flag eq "lines") {
		my @nums  = shift @args;
		my $lines = shift @nums;
		my $start = @$lines[0];
		my $end   = @$lines[1];
		if (!$end) {
			return "-L $start:$filename"
		} else {
			return "-L $start,$end:$filename";
		}
	}
}

# map to `git log` flag options, format the
# command and pass it to `system` builtin
sub git_track {
	my @command = ();
	# iterate through flag options and arguments (if applicable)
	while (my ($flag, $args) = each %flags) {
		my $rflag = &get_format_rflag($flag, $args);
		push @command, $rflag;
	}
	unshift @command, @git_log, @git_log_flags;
	push @command, '--', $filename;
	system @command;
}

# execute `git track` command with flag options
&git_track();
